// Architeuthis Dux (Giant Atlantic Squid)
// Dillon et al
// 2AFC verb / pronoun continuation task

// Do show progress bar (fine! I give in)
var showProgressBar = true;

// Main shuffleSequence definition
var shuffleSequence = seq(
    'consent',
    'intro',
    'shared-intro',
    sepWith("timeoutSep",rshuffle(startsWith('SAPPHARINA'), startsWith('filler'))),
    'debrief'
     );

// Using modified controller coded by Ethan Poole (Umass, 2017)
// Disallows use of mouse for responses.
var DS = 'EPDashedAcceptabilityJudgment';

// Controller settings.
// Parameter settings taken from Staub 2009
var defaults = [
    "EPDashedSentence", {
        mode: 'speeded acceptability',
        display: 'in place',
        blankText: '+',
        wordTime: 1000,
        wordPauseTime: 150
        },
        DS, {randomOrder: false,
        presentHorizontally: true,
        mode: 'speeded acceptability',
        display: 'in place',
        blankText: '+',
        wordTime: 250,
        wordPauseTime: 150,
        timeout: null,
        hasCorrect: 1,
        q: ''}
];

// Add breaks every 24 items
function modifyRunningOrder(ro)
{
    for (var i = 0; i < ro.length; ++i)
    {
        if (i % 24 == 1
            && i > 23
            && i < 250)
        {
            ro[i].push(new DynamicElement(
                "Message",
                {html: "<p>Please take a short break. Press a button to continue when you're ready.</p>", transfer: "keypress"},
            true));
            ro[i].push(new DynamicElement(
                "Separator",
                {transfer: 2500, normalMessage: "Hands in place! Your first sentence of this block will start soon."},
            true));
        }
    }
    return ro;
}

// Items array.
var items = [

["timeoutSep", Separator, { transfer: 250, normalMessage: "", errorMessage: ""}],

["consent", "Form", {consentRequired: true, html: {include: "consent.html"}}],
["intro", "Form", {consentRequired: true, html: {include: "intro.html"}}],
["debrief", "Form", {consentRequired: true, html: {include: "debrief.html"}}],

['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro1.html"}}],
['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro2.html"}}],
['shared-intro', "Form", {consentRequired: false, html: {include: "shared_intro3.html"}}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "Let's try one practice item."]
                         ]}],

['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"The cute cats",as: [['s','was'],['k','were']]}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "How was that? Just try and pick whichever word seems to fit better as the next word of the sentence.  "],
                           ["p", "Many English speakers find 'were' to be a more natural completion. Let's try some more."]
                         ]}],

['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"The nervous employee",as: [['s','was'],['k','were']]}],
['shared-intro', Separator, { transfer: 250, normalMessage: "", errorMessage: ""}, "EPDashedSentence", {s:"+"}, DS, {s:"Mary and John",as: [['s','was'],['k','were']]}],

['shared-intro', Message, {consentRequired: false,
                   html: ["div",
                           ["p", "Alright, that's it for practice! Hit any key when you're ready to begin."]
                        ]}],

['shared-intro',"Separator",{transfer: 2500, normalMessage: "Hands in place! Your first sentence of this block will start soon."}],


//// Shared experimental items + fillers
//// ARCHITEUTHIS: Main Agreement / Reflexive comparison
[["SAPPHARINA-1",1], "EPDashedSentence", {s:"+"}, DS, {s:"Which painting of the sculpture did John say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",1], "EPDashedSentence", {s:"+"}, DS, {s:"Which painting of the sculptures did John say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",1], "EPDashedSentence", {s:"+"}, DS, {s:"Which painting near the sculpture did John say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",1], "EPDashedSentence", {s:"+"}, DS, {s:"Which painting near the sculptures did John say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",1], "EPDashedSentence", {s:"+"}, DS, {s:"Did John say which painting of the sculpture ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",1], "EPDashedSentence", {s:"+"}, DS, {s:"Did John say which painting of the sculptures",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",1], "EPDashedSentence", {s:"+"}, DS, {s:"Did John say which painting near the sculpture ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",1], "EPDashedSentence", {s:"+"}, DS, {s:"Did John say which painting near the sculptures",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",2], "EPDashedSentence", {s:"+"}, DS, {s:"Which picture of the dog did Mary say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",2], "EPDashedSentence", {s:"+"}, DS, {s:"Which picture of the dogs did Mary say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",2], "EPDashedSentence", {s:"+"}, DS, {s:"Which picture near the dog did Mary say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",2], "EPDashedSentence", {s:"+"}, DS, {s:"Which picture near the dogs did Mary say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",2], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mary say which picture of the dog ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",2], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mary say which picture of the dogs ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",2], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mary say which picture near the dog",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",2], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mary say which picture near the dogs",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-1",3], "EPDashedSentence", {s:"+"}, DS, {s:"Which drawing of the flower did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",3], "EPDashedSentence", {s:"+"}, DS, {s:"Which drawing of the flowers did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",3], "EPDashedSentence", {s:"+"}, DS, {s:"Which drawing near the flower did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",3], "EPDashedSentence", {s:"+"}, DS, {s:"Which drawing near the flowers did Kaitlyn say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",3], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which drawing of the flower ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",3], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which drawing of the flowers",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",3], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which drawing near the flower ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",3], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which drawing near the flowers ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-1",4], "EPDashedSentence", {s:"+"}, DS, {s:"Which burglary of the apartment did Brian say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",4], "EPDashedSentence", {s:"+"}, DS, {s:"Which burglary of the apartments did Brian say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",4], "EPDashedSentence", {s:"+"}, DS, {s:"Which burglary near the apartment did Brian say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",4], "EPDashedSentence", {s:"+"}, DS, {s:"Which burglary near the apartments did Brian say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",4], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brian say which burglary of the apartment",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",4], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brian say which burglary of the apartments",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",4], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brian say which burglary near the apartment",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",4], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brian say which burglary near the apartments",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",5], "EPDashedSentence", {s:"+"}, DS, {s:"Which gear of the handmade clock did Chris say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",5], "EPDashedSentence", {s:"+"}, DS, {s:"Which gear of the handmade clocks did Chris say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",5], "EPDashedSentence", {s:"+"}, DS, {s:"Which gear near the handmade clock did Chris say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",5], "EPDashedSentence", {s:"+"}, DS, {s:"Which gear near the handmade clocks did Chris say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",5], "EPDashedSentence", {s:"+"}, DS, {s:"Did Chris say which gear of the handmade clock",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",5], "EPDashedSentence", {s:"+"}, DS, {s:"Did Chris say which gear of the handmade clocks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",5], "EPDashedSentence", {s:"+"}, DS, {s:"Did Chris say which gear near the handmade clock ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",5], "EPDashedSentence", {s:"+"}, DS, {s:"Did Chris say which gear near the handmade clocks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",6], "EPDashedSentence", {s:"+"}, DS, {s:"Which tour of the historic monument did Emily say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",6], "EPDashedSentence", {s:"+"}, DS, {s:"Which tour of the historic monuments did Emily say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",6], "EPDashedSentence", {s:"+"}, DS, {s:"Which tour near the historic monument did Emily say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",6], "EPDashedSentence", {s:"+"}, DS, {s:"Which tour near the historic monuments did Emily say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",6], "EPDashedSentence", {s:"+"}, DS, {s:"Did Emily say which tour of the historic monument",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",6], "EPDashedSentence", {s:"+"}, DS, {s:"Did Emily say which tour of the historic monuments",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",6], "EPDashedSentence", {s:"+"}, DS, {s:"Did Emily say which tour near the historic monument",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",6], "EPDashedSentence", {s:"+"}, DS, {s:"Did Emily say which tour near the historic monuments",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",7], "EPDashedSentence", {s:"+"}, DS, {s:"Which shelf of the crowded bookcase did Jack say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",7], "EPDashedSentence", {s:"+"}, DS, {s:"Which shelf of the crowded bookcases did Jack say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",7], "EPDashedSentence", {s:"+"}, DS, {s:"Which shelf near the crowded bookcase did Jack say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",7], "EPDashedSentence", {s:"+"}, DS, {s:"Which shelf near the crowded bookcases did Jack say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",7], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jack say which shelf of the crowded bookcase",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",7], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jack say which shelf of the crowded bookcases",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",7], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jack say which shelf near the crowded bookcase",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",7], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jack say which shelf near the crowded bookcases",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",8], "EPDashedSentence", {s:"+"}, DS, {s:"Which area of the national park did Jen say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",8], "EPDashedSentence", {s:"+"}, DS, {s:"Which area of the national parks did Jen say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",8], "EPDashedSentence", {s:"+"}, DS, {s:"Which area near the national park did Jen say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",8], "EPDashedSentence", {s:"+"}, DS, {s:"Which area near the national parks did Jen say ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",8], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jen say which area of the national park ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",8], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jen say which area of the national parks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",8], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jen say which area near the national park",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",8], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jen say which area near the national parks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",9], "EPDashedSentence", {s:"+"}, DS, {s:"Which star of the famous constellation did Charlotte say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",9], "EPDashedSentence", {s:"+"}, DS, {s:"Which star of the famous constellations did Charlotte say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",9], "EPDashedSentence", {s:"+"}, DS, {s:"Which star near the famous constellation did Charlotte say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",9], "EPDashedSentence", {s:"+"}, DS, {s:"Which star near the famous constellations did Charlotte say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",9], "EPDashedSentence", {s:"+"}, DS, {s:"Did Charlotte say which star of the famous constellation",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",9], "EPDashedSentence", {s:"+"}, DS, {s:"Did Charlotte say which star of the famous constellations",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",9], "EPDashedSentence", {s:"+"}, DS, {s:"Did Charlotte say which star near the famous constellation",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",9], "EPDashedSentence", {s:"+"}, DS, {s:"Did Charlotte say which star near the famous constellations",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",10], "EPDashedSentence", {s:"+"}, DS, {s:"Which tunnel of the mine did Jacob say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",10], "EPDashedSentence", {s:"+"}, DS, {s:"Which tunnel of the mines did Jacob say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",10], "EPDashedSentence", {s:"+"}, DS, {s:"Which tunnel near the mine did Jacob say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",10], "EPDashedSentence", {s:"+"}, DS, {s:"Which tunnel near the mines did Jacob say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",10], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jacob say which tunnel of the mine ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",10], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jacob say which tunnel of the mines",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",10], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jacob say which tunnel near the mine",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",10], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jacob say which tunnel near the mines",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",11], "EPDashedSentence", {s:"+"}, DS, {s:"Which sculpture of the pyramid did Noah say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",11], "EPDashedSentence", {s:"+"}, DS, {s:"Which sculpture of the pyramids did Noah say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",11], "EPDashedSentence", {s:"+"}, DS, {s:"Which sculpture near the pyramid did Noah say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",11], "EPDashedSentence", {s:"+"}, DS, {s:"Which sculpture near the pyramids did Noah say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",11], "EPDashedSentence", {s:"+"}, DS, {s:"Did Noah say which sculpture of the pyramid ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",11], "EPDashedSentence", {s:"+"}, DS, {s:"Did Noah say which sculpture of the pyramids",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",11], "EPDashedSentence", {s:"+"}, DS, {s:"Did Noah say which sculpture near the pyramid",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",11], "EPDashedSentence", {s:"+"}, DS, {s:"Did Noah say which sculpture near the pyramids",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",12], "EPDashedSentence", {s:"+"}, DS, {s:"Which postcard of the old town did Molly say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",12], "EPDashedSentence", {s:"+"}, DS, {s:"Which postcard of the old towns did Molly say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",12], "EPDashedSentence", {s:"+"}, DS, {s:"Which postcard near the old town did Molly say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",12], "EPDashedSentence", {s:"+"}, DS, {s:"Which postcard near the old towns did Molly say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",12], "EPDashedSentence", {s:"+"}, DS, {s:"Did Molly say which postcard of the old town",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",12], "EPDashedSentence", {s:"+"}, DS, {s:"Did Molly say which postcard of the old towns",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",12], "EPDashedSentence", {s:"+"}, DS, {s:"Did Molly say which postcard near the old town",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",12], "EPDashedSentence", {s:"+"}, DS, {s:"Did Molly say which postcard near the old towns",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",13], "EPDashedSentence", {s:"+"}, DS, {s:"Which photo of the stolen yearbook did Nicole say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",13], "EPDashedSentence", {s:"+"}, DS, {s:"Which photo of the stolen yearbooks did Nicole say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",13], "EPDashedSentence", {s:"+"}, DS, {s:"Which photo in the stolen yearbook did Nicole say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",13], "EPDashedSentence", {s:"+"}, DS, {s:"Which photo in the stolen yearbooks did Nicole say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",13], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nicole say which photo of the stolen yearbook",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",13], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nicole say which photo of the stolen yearbooks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",13], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nicole say which photo in the stolen yearbook",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",13], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nicole say which photo in the stolen yearbooks",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",14], "EPDashedSentence", {s:"+"}, DS, {s:"Which assessment of the class did Kyle say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",14], "EPDashedSentence", {s:"+"}, DS, {s:"Which assessment of the classes did Kyle say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",14], "EPDashedSentence", {s:"+"}, DS, {s:"Which assessment in the class did Kyle say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",14], "EPDashedSentence", {s:"+"}, DS, {s:"Which assessment in the classes did Kyle say ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",14], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kyle say which assessment of the class",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",14], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kyle say which assessment of the classes",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",14], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kyle say which assessment in the class ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",14], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kyle say which assessment in the classes",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",15], "EPDashedSentence", {s:"+"}, DS, {s:"Which investigation of the school did Kathy say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",15], "EPDashedSentence", {s:"+"}, DS, {s:"Which investigation of the schools did Kathy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",15], "EPDashedSentence", {s:"+"}, DS, {s:"Which investigation in the school did Kathy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",15], "EPDashedSentence", {s:"+"}, DS, {s:"Which investigation in the schools did Kathy say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",15], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kathy say which investigation of the school",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",15], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kathy say which investigation of the schools",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",15], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kathy say which investigation in the school",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",15], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kathy say which investigation in the schools",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",16], "EPDashedSentence", {s:"+"}, DS, {s:"Which review of the scientific journal did Eric say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",16], "EPDashedSentence", {s:"+"}, DS, {s:"Which review of the scientific journals did Eric say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",16], "EPDashedSentence", {s:"+"}, DS, {s:"Which review in the scientific journal did Eric say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",16], "EPDashedSentence", {s:"+"}, DS, {s:"Which review in the scientific journals did Eric say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",16], "EPDashedSentence", {s:"+"}, DS, {s:"Did Eric say which review of the scientific journal",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",16], "EPDashedSentence", {s:"+"}, DS, {s:"Did Eric say which review of the scientific journals",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",16], "EPDashedSentence", {s:"+"}, DS, {s:"Did Eric say which review in the scientific journal",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",16], "EPDashedSentence", {s:"+"}, DS, {s:"Did Eric say which review in the scientific journals",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",17], "EPDashedSentence", {s:"+"}, DS, {s:"Which artifact of the ancient city did Alex say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",17], "EPDashedSentence", {s:"+"}, DS, {s:"Which artifact of the ancient cities did Alex say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",17], "EPDashedSentence", {s:"+"}, DS, {s:"Which artifact in the ancient city did Alex say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",17], "EPDashedSentence", {s:"+"}, DS, {s:"Which artifact in the ancient cities did Alex say ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",17], "EPDashedSentence", {s:"+"}, DS, {s:"Did Alex say which artifact of the ancient city",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",17], "EPDashedSentence", {s:"+"}, DS, {s:"Did Alex say which artifact of the ancient cities",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",17], "EPDashedSentence", {s:"+"}, DS, {s:"Did Alex say which artifact in the ancient city",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",17], "EPDashedSentence", {s:"+"}, DS, {s:"Did Alex say which artifact in the ancient cities",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",18], "EPDashedSentence", {s:"+"}, DS, {s:"Which room of the ship did Ana say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",18], "EPDashedSentence", {s:"+"}, DS, {s:"Which room of the ships did Ana say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",18], "EPDashedSentence", {s:"+"}, DS, {s:"Which room in the ship did Ana say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",18], "EPDashedSentence", {s:"+"}, DS, {s:"Which room in the ships did Ana say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",18], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ana say which room of the ship ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",18], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ana say which room of the ships",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",18], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ana say which room in the ship",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",18], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ana say which room in the ships",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",19], "EPDashedSentence", {s:"+"}, DS, {s:"Which advertisement of the wildlife magazine did Jason say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",19], "EPDashedSentence", {s:"+"}, DS, {s:"Which advertisement of the wildlife magazines did Jason say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",19], "EPDashedSentence", {s:"+"}, DS, {s:"Which advertisement in the wildlife magazine did Jason say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",19], "EPDashedSentence", {s:"+"}, DS, {s:"Which advertisement in the wildlife magazines did Jason say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",19], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jason say which advertisement of the wildlife magazine ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",19], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jason say which advertisement of the wildlife magazines",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",19], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jason say which advertisement in the wildlife magazine",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",19], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jason say which advertisement in the wildlife magazines",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",20], "EPDashedSentence", {s:"+"}, DS, {s:"Which school of the local district did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",20], "EPDashedSentence", {s:"+"}, DS, {s:"Which school of the local districts did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",20], "EPDashedSentence", {s:"+"}, DS, {s:"Which school in the local district did Kaitlyn say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",20], "EPDashedSentence", {s:"+"}, DS, {s:"Which school in the local districts did Kaitlyn say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",20], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which school of the local district ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",20], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which school of the local districts",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",20], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which school in the local district",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",20], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kaitlyn say which school in the local districts",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",21], "EPDashedSentence", {s:"+"}, DS, {s:"Which announcement of the emergency broadcast did Brendan say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",21], "EPDashedSentence", {s:"+"}, DS, {s:"Which announcement of the emergency broadcasts did Brendan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",21], "EPDashedSentence", {s:"+"}, DS, {s:"Which announcement in the emergency broadcast did Brendan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",21], "EPDashedSentence", {s:"+"}, DS, {s:"Which announcement in the emergency broadcasts did Brendan say ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",21], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brendan say which announcement of the emergency broadcast",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",21], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brendan say which announcement of the emergency broadcasts",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",21], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brendan say which announcement in the emergency broadcast",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",21], "EPDashedSentence", {s:"+"}, DS, {s:"Did Brendan say which announcement in the emergency broadcasts",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",22], "EPDashedSentence", {s:"+"}, DS, {s:"Which sketch of the lost book did Trevor say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",22], "EPDashedSentence", {s:"+"}, DS, {s:"Which sketch of the lost books did Trevor say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",22], "EPDashedSentence", {s:"+"}, DS, {s:"Which sketch in the lost book did Trevor say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",22], "EPDashedSentence", {s:"+"}, DS, {s:"Which sketch in the lost books did Trevor say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",22], "EPDashedSentence", {s:"+"}, DS, {s:"Did Trevor say which sketch of the lost book",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",22], "EPDashedSentence", {s:"+"}, DS, {s:"Did Trevor say which sketch of the lost books",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",22], "EPDashedSentence", {s:"+"}, DS, {s:"Did Trevor say which sketch in the lost book",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",22], "EPDashedSentence", {s:"+"}, DS, {s:"Did Trevor say which sketch in the lost books",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",23], "EPDashedSentence", {s:"+"}, DS, {s:"Which quote of the inspirational speech did Ally say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",23], "EPDashedSentence", {s:"+"}, DS, {s:"Which quote of the inspirational speeches did Ally say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",23], "EPDashedSentence", {s:"+"}, DS, {s:"Which quote in the inspirational speech did Ally say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",23], "EPDashedSentence", {s:"+"}, DS, {s:"Which quote in the inspirational speeches did Ally say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",23], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ally say which quote of the inspirational speech",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",23], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ally say which quote of the inspirational speeches",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",23], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ally say which quote in the inspirational speech",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",23], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ally say which quote in the inspirational speeches",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",24], "EPDashedSentence", {s:"+"}, DS, {s:"Which goal of the research project did Vincent say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",24], "EPDashedSentence", {s:"+"}, DS, {s:"Which goal of the research projects did Vincent say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",24], "EPDashedSentence", {s:"+"}, DS, {s:"Which goal in the research project did Vincent say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",24], "EPDashedSentence", {s:"+"}, DS, {s:"Which goal in the research projects did Vincent say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",24], "EPDashedSentence", {s:"+"}, DS, {s:"Did Vincent say which goal of the research project",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",24], "EPDashedSentence", {s:"+"}, DS, {s:"Did Vincent say which goal of the research projects",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",24], "EPDashedSentence", {s:"+"}, DS, {s:"Did Vincent say which goal in the research project ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",24], "EPDashedSentence", {s:"+"}, DS, {s:"Did Vincent say which goal in the research projects",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",25], "EPDashedSentence", {s:"+"}, DS, {s:"Which photographer of the model did Julia say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",25], "EPDashedSentence", {s:"+"}, DS, {s:"Which photographer of the models did Julia say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",25], "EPDashedSentence", {s:"+"}, DS, {s:"Which photographer near the model did Julia say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",25], "EPDashedSentence", {s:"+"}, DS, {s:"Which photographer near the models did Julia say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",25], "EPDashedSentence", {s:"+"}, DS, {s:"Did Julia say which photographer of the model ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",25], "EPDashedSentence", {s:"+"}, DS, {s:"Did Julia say which photographer of the models",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",25], "EPDashedSentence", {s:"+"}, DS, {s:"Did Julia say which photographer near the model",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",25], "EPDashedSentence", {s:"+"}, DS, {s:"Did Julia say which photographer near the models",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",26], "EPDashedSentence", {s:"+"}, DS, {s:"Which architect of the new building did Jeremy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",26], "EPDashedSentence", {s:"+"}, DS, {s:"Which architect of the new buildings did Jeremy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",26], "EPDashedSentence", {s:"+"}, DS, {s:"Which architect near the new building did Jeremy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",26], "EPDashedSentence", {s:"+"}, DS, {s:"Which architect near the new buildings did Jeremy say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",26], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jeremy say which architect of the new building",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",26], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jeremy say which architect of the new buildings",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",26], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jeremy say which architect near the new building",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",26], "EPDashedSentence", {s:"+"}, DS, {s:"Did Jeremy say which architect near the new buildings",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",27], "EPDashedSentence", {s:"+"}, DS, {s:"Which commander of the ship did Ethan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",27], "EPDashedSentence", {s:"+"}, DS, {s:"Which commander of the ships did Ethan say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",27], "EPDashedSentence", {s:"+"}, DS, {s:"Which commander near the ship did Ethan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",27], "EPDashedSentence", {s:"+"}, DS, {s:"Which commander near the ships did Ethan say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",27], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ethan say which commander of the ship ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",27], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ethan say which commander of the ships",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",27], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ethan say which commander near the ship",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",27], "EPDashedSentence", {s:"+"}, DS, {s:"Did Ethan say which commander near the ships",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",28], "EPDashedSentence", {s:"+"}, DS, {s:"Which driver of the bus did Amy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",28], "EPDashedSentence", {s:"+"}, DS, {s:"Which driver of the buses did Amy say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",28], "EPDashedSentence", {s:"+"}, DS, {s:"Which driver near the bus did Amy say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",28], "EPDashedSentence", {s:"+"}, DS, {s:"Which driver near the buses did Amy say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",28], "EPDashedSentence", {s:"+"}, DS, {s:"Did Amy say which driver of the bus ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",28], "EPDashedSentence", {s:"+"}, DS, {s:"Did Amy say which driver of the buses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",28], "EPDashedSentence", {s:"+"}, DS, {s:"Did Amy say which driver near the bus",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",28], "EPDashedSentence", {s:"+"}, DS, {s:"Did Amy say which driver near the buses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",29], "EPDashedSentence", {s:"+"}, DS, {s:"Which guard of the exhibit did Scott say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",29], "EPDashedSentence", {s:"+"}, DS, {s:"Which guard of the exhibits did Scott say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",29], "EPDashedSentence", {s:"+"}, DS, {s:"Which guard near the exhibit did Scott say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",29], "EPDashedSentence", {s:"+"}, DS, {s:"Which guard near the exhibits did Scott say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",29], "EPDashedSentence", {s:"+"}, DS, {s:"Did Scott say which guard of the exhibit",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",29], "EPDashedSentence", {s:"+"}, DS, {s:"Did Scott say which guard of the exhibits",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",29], "EPDashedSentence", {s:"+"}, DS, {s:"Did Scott say which guard near the exhibit",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",29], "EPDashedSentence", {s:"+"}, DS, {s:"Did Scott say which guard near the exhibits",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",30], "EPDashedSentence", {s:"+"}, DS, {s:"Which resident of the overpriced townhouse did Rachel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",30], "EPDashedSentence", {s:"+"}, DS, {s:"Which resident of the overpriced townhouses did Rachel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",30], "EPDashedSentence", {s:"+"}, DS, {s:"Which resident near the overpriced townhouse did Rachel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",30], "EPDashedSentence", {s:"+"}, DS, {s:"Which resident near the overpriced townhouses did Rachel say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",30], "EPDashedSentence", {s:"+"}, DS, {s:"Did Rachel say which resident of the overpriced townhouse",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",30], "EPDashedSentence", {s:"+"}, DS, {s:"Did Rachel say which resident of the overpriced townhouses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",30], "EPDashedSentence", {s:"+"}, DS, {s:"Did Rachel say which resident near the overpriced townhouse",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",30], "EPDashedSentence", {s:"+"}, DS, {s:"Did Rachel say which resident near the overpriced townhouses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",31], "EPDashedSentence", {s:"+"}, DS, {s:"Which designer of the dress did Lisa say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",31], "EPDashedSentence", {s:"+"}, DS, {s:"Which designer of the dresses did Lisa say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",31], "EPDashedSentence", {s:"+"}, DS, {s:"Which designer near the dress did Lisa say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",31], "EPDashedSentence", {s:"+"}, DS, {s:"Which designer near the dresses did Lisa say ",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",31], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lisa say which designer of the dress",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",31], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lisa say which designer of the dresses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",31], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lisa say which designer near the dress",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",31], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lisa say which designer near the dresses",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",32], "EPDashedSentence", {s:"+"}, DS, {s:"Which missionary of the church did Drew say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",32], "EPDashedSentence", {s:"+"}, DS, {s:"Which missionary of the churches did Drew say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",32], "EPDashedSentence", {s:"+"}, DS, {s:"Which missionary near the church did Drew say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",32], "EPDashedSentence", {s:"+"}, DS, {s:"Which missionary near the churches did Drew say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",32], "EPDashedSentence", {s:"+"}, DS, {s:"Did Drew say which missionary of the church",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",32], "EPDashedSentence", {s:"+"}, DS, {s:"Did Drew say which missionary of the churches ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",32], "EPDashedSentence", {s:"+"}, DS, {s:"Did Drew say which missionary near the church",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",32], "EPDashedSentence", {s:"+"}, DS, {s:"Did Drew say which missionary near the churches",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",33], "EPDashedSentence", {s:"+"}, DS, {s:"Which witness of the robbery did Evan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",33], "EPDashedSentence", {s:"+"}, DS, {s:"Which witness of the robberies did Evan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",33], "EPDashedSentence", {s:"+"}, DS, {s:"Which witness near the robbery did Evan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",33], "EPDashedSentence", {s:"+"}, DS, {s:"Which witness near the robberies did Evan say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",33], "EPDashedSentence", {s:"+"}, DS, {s:"Did Evan say which witness of the robbery ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",33], "EPDashedSentence", {s:"+"}, DS, {s:"Did Evan say which witness of the robberies ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",33], "EPDashedSentence", {s:"+"}, DS, {s:"Did Evan say which witness near the robbery",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",33], "EPDashedSentence", {s:"+"}, DS, {s:"Did Evan say which witness near the robberies",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-1",34], "EPDashedSentence", {s:"+"}, DS, {s:"Which hiker of the dangerous mountain did Miguel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",34], "EPDashedSentence", {s:"+"}, DS, {s:"Which hiker of the dangerous mountains did Miguel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",34], "EPDashedSentence", {s:"+"}, DS, {s:"Which hiker near the dangerous mountain did Miguel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",34], "EPDashedSentence", {s:"+"}, DS, {s:"Which hiker near the dangerous mountains did Miguel say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",34], "EPDashedSentence", {s:"+"}, DS, {s:"Did Miguel say which hiker of the dangerous mountain",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",34], "EPDashedSentence", {s:"+"}, DS, {s:"Did Miguel say which hiker of the dangerous mountains",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",34], "EPDashedSentence", {s:"+"}, DS, {s:"Did Miguel say which hiker near the dangerous mountain",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",34], "EPDashedSentence", {s:"+"}, DS, {s:"Did Miguel say which hiker near the dangerous mountains",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",35], "EPDashedSentence", {s:"+"}, DS, {s:"Which pilot of the plane did Max say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",35], "EPDashedSentence", {s:"+"}, DS, {s:"Which pilot of the planes did Max say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",35], "EPDashedSentence", {s:"+"}, DS, {s:"Which pilot near the plane did Max say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",35], "EPDashedSentence", {s:"+"}, DS, {s:"Which pilot near the planes did Max say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",35], "EPDashedSentence", {s:"+"}, DS, {s:"Did Max say which pilot of the plane",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",35], "EPDashedSentence", {s:"+"}, DS, {s:"Did Max say which pilot of the planes ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",35], "EPDashedSentence", {s:"+"}, DS, {s:"Did Max say which pilot near the plane",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",35], "EPDashedSentence", {s:"+"}, DS, {s:"Did Max say which pilot near the planes",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",36], "EPDashedSentence", {s:"+"}, DS, {s:"Which supplier of the local supermarket did Harry say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",36], "EPDashedSentence", {s:"+"}, DS, {s:"Which supplier of the local supermarkets did Harry say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",36], "EPDashedSentence", {s:"+"}, DS, {s:"Which supplier near the local supermarket did Harry say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",36], "EPDashedSentence", {s:"+"}, DS, {s:"Which supplier near the local supermarkets did Harry say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",36], "EPDashedSentence", {s:"+"}, DS, {s:"Did Harry say which supplier of the local supermarket",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",36], "EPDashedSentence", {s:"+"}, DS, {s:"Did Harry say which supplier of the local supermarkets",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",36], "EPDashedSentence", {s:"+"}, DS, {s:"Did Harry say which supplier near the local supermarket",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",36], "EPDashedSentence", {s:"+"}, DS, {s:"Did Harry say which supplier near the local supermarkets",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",37], "EPDashedSentence", {s:"+"}, DS, {s:"Which police officer of the bad neighborhood did Susan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",37], "EPDashedSentence", {s:"+"}, DS, {s:"Which police officer of the bad neighborhoods did Susan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",37], "EPDashedSentence", {s:"+"}, DS, {s:"Which police officer in the bad neighborhood did Susan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",37], "EPDashedSentence", {s:"+"}, DS, {s:"Which police officer in the bad neighborhoods did Susan say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",37], "EPDashedSentence", {s:"+"}, DS, {s:"Did Susan say which police officer of the bad neighborhood ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",37], "EPDashedSentence", {s:"+"}, DS, {s:"Did Susan say which police officer of the bad neighborhoods",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",37], "EPDashedSentence", {s:"+"}, DS, {s:"Did Susan say which police officer in the bad neighborhood",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",37], "EPDashedSentence", {s:"+"}, DS, {s:"Did Susan say which police officer in the bad neighborhoods",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",38], "EPDashedSentence", {s:"+"}, DS, {s:"Which farmer of the field did Mark say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",38], "EPDashedSentence", {s:"+"}, DS, {s:"Which farmer of the fields did Mark say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",38], "EPDashedSentence", {s:"+"}, DS, {s:"Which farmer in the field did Mark say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",38], "EPDashedSentence", {s:"+"}, DS, {s:"Which farmer in the fields did Mark say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",38], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mark say which farmer of the field ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",38], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mark say which farmer of the fields ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",38], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mark say which farmer in the field",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",38], "EPDashedSentence", {s:"+"}, DS, {s:"Did Mark say which farmer in the fields",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",39], "EPDashedSentence", {s:"+"}, DS, {s:"Which supervisor of the training program did Daniel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",39], "EPDashedSentence", {s:"+"}, DS, {s:"Which supervisor of the training programs did Daniel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",39], "EPDashedSentence", {s:"+"}, DS, {s:"Which supervisor in the training program did Daniel say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",39], "EPDashedSentence", {s:"+"}, DS, {s:"Which supervisor in the training programs did Daniel say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",39], "EPDashedSentence", {s:"+"}, DS, {s:"Did Daniel say which supervisor of the training program",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",39], "EPDashedSentence", {s:"+"}, DS, {s:"Did Daniel say which supervisor of the training programs",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",39], "EPDashedSentence", {s:"+"}, DS, {s:"Did Daniel say which supervisor in the training program",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",39], "EPDashedSentence", {s:"+"}, DS, {s:"Did Daniel say which supervisor in the training programs",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",40], "EPDashedSentence", {s:"+"}, DS, {s:"Which character of the animated movie did Bill say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",40], "EPDashedSentence", {s:"+"}, DS, {s:"Which character of the animated movies did Bill say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",40], "EPDashedSentence", {s:"+"}, DS, {s:"Which character in the animated movie did Bill say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",40], "EPDashedSentence", {s:"+"}, DS, {s:"Which character in the animated movies did Bill say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",40], "EPDashedSentence", {s:"+"}, DS, {s:"Did Bill say which character of the animated movie",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",40], "EPDashedSentence", {s:"+"}, DS, {s:"Did Bill say which character of the animated movies",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",40], "EPDashedSentence", {s:"+"}, DS, {s:"Did Bill say which character in the animated movie",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",40], "EPDashedSentence", {s:"+"}, DS, {s:"Did Bill say which character in the animated movies",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",41], "EPDashedSentence", {s:"+"}, DS, {s:"Which explorer of the cave did Lauren say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",41], "EPDashedSentence", {s:"+"}, DS, {s:"Which explorer of the caves did Lauren say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",41], "EPDashedSentence", {s:"+"}, DS, {s:"Which explorer in the cave did Lauren say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",41], "EPDashedSentence", {s:"+"}, DS, {s:"Which explorer in the caves did Lauren say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",41], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lauren say which explorer of the cave",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",41], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lauren say which explorer of the caves",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",41], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lauren say which explorer in the cave",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",41], "EPDashedSentence", {s:"+"}, DS, {s:"Did Lauren say which explorer in the caves",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",42], "EPDashedSentence", {s:"+"}, DS, {s:"Which thief of the surveillance tape did Nick say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",42], "EPDashedSentence", {s:"+"}, DS, {s:"Which thief of the surveillance tapes did Nick say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",42], "EPDashedSentence", {s:"+"}, DS, {s:"Which thief in the surveillance tape did Nick say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",42], "EPDashedSentence", {s:"+"}, DS, {s:"Which thief in the surveillance tapes did Nick say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",42], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nick say which thief of the surveillance tape",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",42], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nick say which thief of the surveillance tapes",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",42], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nick say which thief in the surveillance tape",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",42], "EPDashedSentence", {s:"+"}, DS, {s:"Did Nick say which thief in the surveillance tapes",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",43], "EPDashedSentence", {s:"+"}, DS, {s:"Which organizer of the protest did Morgan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",43], "EPDashedSentence", {s:"+"}, DS, {s:"Which organizer of the protests did Morgan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",43], "EPDashedSentence", {s:"+"}, DS, {s:"Which organizer in the protest did Morgan say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",43], "EPDashedSentence", {s:"+"}, DS, {s:"Which organizer in the protests did Morgan say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",43], "EPDashedSentence", {s:"+"}, DS, {s:"Did Morgan say which organizer of the protest",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",43], "EPDashedSentence", {s:"+"}, DS, {s:"Did Morgan say which organizer of the protests",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",43], "EPDashedSentence", {s:"+"}, DS, {s:"Did Morgan say which organizer in the protest",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",43], "EPDashedSentence", {s:"+"}, DS, {s:"Did Morgan say which organizer in the protests",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",44], "EPDashedSentence", {s:"+"}, DS, {s:"Which leader of the conservation movement did Justin say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",44], "EPDashedSentence", {s:"+"}, DS, {s:"Which leader of the conversation movements did Justin say ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",44], "EPDashedSentence", {s:"+"}, DS, {s:"Which leader in the conservation movement did Justin say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",44], "EPDashedSentence", {s:"+"}, DS, {s:"Which leader in the conservation movements did Justin say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",44], "EPDashedSentence", {s:"+"}, DS, {s:"Did Justin say which leader of the conservation movement",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",44], "EPDashedSentence", {s:"+"}, DS, {s:"Did Justin say which leader of the conservation movements",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",44], "EPDashedSentence", {s:"+"}, DS, {s:"Did Justin say which leader in the conservation movement",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",44], "EPDashedSentence", {s:"+"}, DS, {s:"Did Justin say which leader in the conservation movements",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",45], "EPDashedSentence", {s:"+"}, DS, {s:"Which producer of the documentary did Paige say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",45], "EPDashedSentence", {s:"+"}, DS, {s:"Which producer of the documentaries did Paige say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",45], "EPDashedSentence", {s:"+"}, DS, {s:"Which producer in the documentary did Paige say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",45], "EPDashedSentence", {s:"+"}, DS, {s:"Which producer in the documentaries did Paige say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",45], "EPDashedSentence", {s:"+"}, DS, {s:"Did Paige say which producer of the documentary",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",45], "EPDashedSentence", {s:"+"}, DS, {s:"Did Paige say which producer of the documentaries",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",45], "EPDashedSentence", {s:"+"}, DS, {s:"Did Paige say which producer in the documentary",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",45], "EPDashedSentence", {s:"+"}, DS, {s:"Did Paige say which producer in the documentaries",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",46], "EPDashedSentence", {s:"+"}, DS, {s:"Which report of the confidential file did Kim say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",46], "EPDashedSentence", {s:"+"}, DS, {s:"Which report of the confidential files did Kim say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",46], "EPDashedSentence", {s:"+"}, DS, {s:"Which report in the confidential file did Kim say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",46], "EPDashedSentence", {s:"+"}, DS, {s:"Which report in the confidential files did Kim say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",46], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kim say which report of the confidential file ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",46], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kim say which report of the confidential files",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",46], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kim say which report in the confidential file",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",46], "EPDashedSentence", {s:"+"}, DS, {s:"Did Kim say which report in the confidential files",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",47], "EPDashedSentence", {s:"+"}, DS, {s:"Which executive of the suspected company did Aaron say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",47], "EPDashedSentence", {s:"+"}, DS, {s:"Which executive of the suspected companies did Aaron say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",47], "EPDashedSentence", {s:"+"}, DS, {s:"Which executive in the suspected company did Aaron say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",47], "EPDashedSentence", {s:"+"}, DS, {s:"Which executive in the suspected companies did Aaron say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",47], "EPDashedSentence", {s:"+"}, DS, {s:"Did Aaron say which executive of the suspected company",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",47], "EPDashedSentence", {s:"+"}, DS, {s:"Did Aaron say which executive of the suspected companies",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",47], "EPDashedSentence", {s:"+"}, DS, {s:"Did Aaron say which executive in the suspected company",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",47], "EPDashedSentence", {s:"+"}, DS, {s:"Did Aaron say which executive in the suspected companies",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-1",48], "EPDashedSentence", {s:"+"}, DS, {s:"Which participant of the tournament did Katie say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-2",48], "EPDashedSentence", {s:"+"}, DS, {s:"Which participant of the tournaments did Katie say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-3",48], "EPDashedSentence", {s:"+"}, DS, {s:"Which participant in the tournament did Katie say",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-4",48], "EPDashedSentence", {s:"+"}, DS, {s:"Which participant in the tournaments did Katie say",as: [['s','were'],['k','was']]}],
[["SAPPHARINA-5",48], "EPDashedSentence", {s:"+"}, DS, {s:"Did Katie say which participant of the tournament",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-6",48], "EPDashedSentence", {s:"+"}, DS, {s:"Did Katie say which participant of the tournaments",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-7",48], "EPDashedSentence", {s:"+"}, DS, {s:"Did Katie say which participant in the tournament ",as: [['s','were'],['k','was']]}], 
[["SAPPHARINA-8",48], "EPDashedSentence", {s:"+"}, DS, {s:"Did Katie say which participant in the tournaments",as: [['s','were'],['k','was']]}], 


["filler-49", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the books on the table did John think ",as: [['s','were'],['k','was']]}], 
["filler-50", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the games in the tournament did Austin think ",as: [['s','were'],['k','was']]}], 
["filler-51", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the dances at the competition did Naomi say ",as: [['s','were'],['k','was']]}], 
["filler-52", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the professors from the university did Megan think ",as: [['s','were'],['k','was']]}],
["filler-53", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the keys in the drawer did George know",as: [['s','were'],['k','was']]}], 
["filler-54", "EPDashedSentence", {s:"+"}, DS, {s:"Which of the nurses in the operating room did Cassie think",as: [['s','were'],['k','was']]}], 
["filler-55", "EPDashedSentence", {s:"+"}, DS, {s:"Which doctor did Mason think the patients at the hospital ",as: [['s','were'],['k','was']]}], 
["filler-56", "EPDashedSentence", {s:"+"}, DS, {s:"Which composer did Riley think the musicians in the orchestra",as: [['s','were'],['k','was']]}], 
["filler-57", "EPDashedSentence", {s:"+"}, DS, {s:"Which recipes did Julian think the chefs at the restaurant",as: [['s','were'],['k','was']]}], 
["filler-58", "EPDashedSentence", {s:"+"}, DS, {s:"Which software update did Nate know the programmers at the company",as: [['s','were'],['k','was']]}], 
["filler-59", "EPDashedSentence", {s:"+"}, DS, {s:"Which horses did Charles think the trainer at the farm ",as: [['s','were'],['k','was']]}], 
["filler-60", "EPDashedSentence", {s:"+"}, DS, {s:"Which advertisements did Andy know the executives of the brand",as: [['s','were'],['k','was']]}],
["filler-61", "EPDashedSentence", {s:"+"}, DS, {s:"Which skills did Nancy know the interviewers at the agency",as: [['s','were'],['k','was']]}], 
["filler-62", "EPDashedSentence", {s:"+"}, DS, {s:"Which chores did Jess think the boys of the family",as: [['s','were'],['k','was']]}], 
["filler-63", "EPDashedSentence", {s:"+"}, DS, {s:"Which experiments did Pat think the scientists in the lab",as: [['s','were'],['k','was']]}], 
["filler-64", "EPDashedSentence", {s:"+"}, DS, {s:"Which flight attendants did Jeff say the pilot of the plane",as: [['s','were'],['k','was']]}], 
["filler-65", "EPDashedSentence", {s:"+"}, DS, {s:"Which swimmer did Ken say the lifeguards at the beach ",as: [['s','were'],['k','was']]}], 
["filler-66", "EPDashedSentence", {s:"+"}, DS, {s:"Which recruits did Janet think the officers of the police station ",as: [['s','were'],['k','was']]}], 
["filler-67", "EPDashedSentence", {s:"+"}, DS, {s:"Which suggestions did Jose say the director of the program",as: [['s','were'],['k','was']]}], 
["filler-68", "EPDashedSentence", {s:"+"}, DS, {s:"Which prescriptions on the counter did Tara think the pharmacists",as: [['s','were'],['k','was']]}],
["filler-69", "EPDashedSentence", {s:"+"}, DS, {s:"Which trainees from the supermarket did Keith think the managers ",as: [['s','were'],['k','was']]}], 
["filler-70", "EPDashedSentence", {s:"+"}, DS, {s:"Which cabinets in the kitchen did Arthur think the snacks ",as: [['s','were'],['k','was']]}], 
["filler-71", "EPDashedSentence", {s:"+"}, DS, {s:"Which contributor to the campaigns did Zach say the politicians",as: [['s','were'],['k','was']]}], 
["filler-72", "EPDashedSentence", {s:"+"}, DS, {s:"Which pages of the recovered book did Kathy know the historians",as: [['s','were'],['k','was']]}], 
["filler-73", "EPDashedSentence", {s:"+"}, DS, {s:"Which trails of the mountain did Ruth think the hikers",as: [['s','were'],['k','was']]}], 
["filler-74", "EPDashedSentence", {s:"+"}, DS, {s:"Which mechanics at the garage did Tom think the customers",as: [['s','were'],['k','was']]}], 
["filler-75", "EPDashedSentence", {s:"+"}, DS, {s:"Did Diana know which classrooms in the school the janitors",as: [['s','were'],['k','was']]}], 
["filler-76", "EPDashedSentence", {s:"+"}, DS, {s:"Did Logan mention which entrances of the building the residents ",as: [['s','were'],['k','was']]}],
["filler-77", "EPDashedSentence", {s:"+"}, DS, {s:"Did Jane say which assistants in the lab the supervisors ",as: [['s','were'],['k','was']]}], 
["filler-78", "EPDashedSentence", {s:"+"}, DS, {s:"Did Gabe know which cooks at the restaurant the owner",as: [['s','were'],['k','was']]}], 
["filler-79", "EPDashedSentence", {s:"+"}, DS, {s:"Did Laura say which forecast of the storms the meteorologist",as: [['s','were'],['k','was']]}], 
["filler-80", "EPDashedSentence", {s:"+"}, DS, {s:"Did Michelle know which members of the jury the defendant ",as: [['s','were'],['k','was']]}], 
["filler-81", "EPDashedSentence", {s:"+"}, DS, {s:"Did Eli mention who the investigators from the government",as: [['s','were'],['k','was']]}], 
["filler-82", "EPDashedSentence", {s:"+"}, DS, {s:"Did Tom mention who the referees at the game",as: [['s','were'],['k','was']]}], 
["filler-83", "EPDashedSentence", {s:"+"}, DS, {s:"Did Lucy mention who the firefighters in the house",as: [['s','were'],['k','was']]}], 
["filler-84", "EPDashedSentence", {s:"+"}, DS, {s:"Did Helen say who the lawsuits from the small businesses",as: [['s','were'],['k','was']]}],
["filler-85", "EPDashedSentence", {s:"+"}, DS, {s:"Did Maddie mention who the neighbors of the celebrity",as: [['s','were'],['k','was']]}], 
["filler-86", "EPDashedSentence", {s:"+"}, DS, {s:"Did Owen mention who the editors of the journal",as: [['s','were'],['k','was']]}], 
["filler-87", "EPDashedSentence", {s:"+"}, DS, {s:"Did Derek mention who the tickets to the play ",as: [['s','were'],['k','was']]}], 
["filler-88", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Ian think the advocates from the organization ",as: [['s','were'],['k','was']]}], 
["filler-89", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Parker think the political cartoons from the newspaper",as: [['s','were'],['k','was']]}], 
["filler-90", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Mia think the gifts from the charity",as: [['s','were'],['k','was']]}], 
["filler-91", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Blake think the students on the bus",as: [['s','were'],['k','was']]}], 
["filler-92", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Tyler think the workers at the construction site ",as: [['s','were'],['k','was']]}],
["filler-93", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Luke think the maids of the wealthy family ",as: [['s','were'],['k','was']]}], 
["filler-94", "EPDashedSentence", {s:"+"}, DS, {s:"Who did Connor think the columnists from the unreliable website",as: [['s','were'],['k','was']]}], 
["filler-95", "EPDashedSentence", {s:"+"}, DS, {s:"Which inmates at the prison did Bill think",as: [['s','were'],['k','was']]}], 
["filler-96", "EPDashedSentence", {s:"+"}, DS, {s:"Which actors from the new movie did Rob think",as: [['s','were'],['k','was']]}], 
["filler-97", "EPDashedSentence", {s:"+"}, DS, {s:"Which classrooms above the old gymnasium did Jason think",as: [['s','were'],['k','was']]}], 
["filler-98", "EPDashedSentence", {s:"+"}, DS, {s:"Which trespassers on the abandoned property did Molly think",as: [['s','were'],['k','was']]}], 
["filler-99", "EPDashedSentence", {s:"+"}, DS, {s:"Which important documents on the computer did John think ",as: [['s','were'],['k','was']]}], 
["filler-100", "EPDashedSentence", {s:"+"}, DS, {s:"Which solutions to the economic crisis did Heather think ",as: [['s','were'],['k','was']]}],
["filler-101", "EPDashedSentence", {s:"+"}, DS, {s:"Which stores in the shopping center did Adam know ",as: [['s','were'],['k','was']]}], 
["filler-102", "EPDashedSentence", {s:"+"}, DS, {s:"Did Erika know which outlets under the counter ",as: [['s','were'],['k','was']]}], 
["filler-103", "EPDashedSentence", {s:"+"}, DS, {s:"Did Chase say which estimates of the expenses ",as: [['s','were'],['k','was']]}], 
["filler-104", "EPDashedSentence", {s:"+"}, DS, {s:"Did Emma know which departments of the college",as: [['s','were'],['k','was']]}], 
["filler-105", "EPDashedSentence", {s:"+"}, DS, {s:"Did Maya say which airports near the city",as: [['s','were'],['k','was']]}], 
["filler-106", "EPDashedSentence", {s:"+"}, DS, {s:"Did Peter say which shipments of the new product",as: [['s','were'],['k','was']]}], 
["filler-107", "EPDashedSentence", {s:"+"}, DS, {s:"Did Luis know which editions of the book ",as: [['s','were'],['k','was']]}], 
["filler-108", "EPDashedSentence", {s:"+"}, DS, {s:"Did Lily mention which neighborhoods in the city",as: [['s','were'],['k','was']]}]
];
